name: Empower10
favicon: null
layout_spectrum: 0.7290641865693033
typography_spectrum: 0.798574207816273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2d9e1'
    - '#ffffff'
    - '#7e7e7e'
    - '#a6abaf'
    - '#050505'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.46521480777300894
  rhythmicContrast: 0.8372035683132708
purpose: []
